version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./data:/etc/nginx
    networks:
      nginx:
        aliases:
          - nginx
    ports:
      - target: 80
        published: 80
        mode: host

networks:
  nginx:
    name: nginx
    attachable: true
