version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: piriquitin
    ports:
      - target: 27017
        published: 27017
        mode: host
    volumes:
      - mongo:/etc/mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: piriquitin
      ME_CONFIG_MONGODB_URL: mongodb://mongo:piriquitin@mongo:27017/

volumes:
  mongo:
